name: Build

on:
  push:
    branches:
      - 'develop'
      - 'main'
      - 'release/**'
  pull_request:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
      packages: write

    steps:
      - name: Gen Badge
        uses: emibcn/badge-action@v2.0.2
        with:
          label: 'Test coverage'
          status: '53.4%'
          color: 'blue,555,daf'
          path: 'coverage.svg'

      - name: Upload Artifact
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage.svg
          path: coverage.svg

      - name: Append Badge to Summary
        run: |
          id='${{ steps.artifact.outputs.artifact-id }}'
          url="https://api.github.com/repos/gw-kit/delta-coverage-action/actions/artifacts/$id/zip"
          echo "Badge:" >> $GITHUB_STEP_SUMMARY
          echo "![Test coverage]($url)" >> $GITHUB_STEP_SUMMARY
