name: Build

on:
  push:
    branches:
      - 'develop'
      - 'main'
      - 'release/**'
  pull_request:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delta Coverage Action
        uses: gw-kit/delta-coverage-action@test-badges
        with:
          summary-report-base-path: 'summaries/'

      - name: Upload Artifact
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-gen.svg
          path: coverage-gen.svg
