name: Build

on:
  push:
    branches:
      - 'develop'
      - 'main'
      - 'release/**'
  pull_request:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
      packages: write

    steps:
      - name: Gen Badge
        uses: emibcn/badge-action@v2.0.2
        with:
          label: 'Test coverage'
          status: '53.4%'
          color: 'blue,555,daf'
          path: 'coverage.svg'

      - name: Append Badge to Summary
        run: |
          echo "![Test coverage](coverage.svg)" >> $GITHUB_STEP_SUMMARY

      - name: Append with script
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const badge = fs.readFileSync('coverage.svg', 'utf8');
            const summary = `${{ github.step_summary }}`;
            const newSummary = `${summary}\n${badge}`;
            fs.writeFileSync('coverage.svg', newSummary);
